name: Build Windows

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install PySide6
          pip install python-mpv

      - name: Build Rify
        shell: pwsh
        run: |
          pyinstaller --name Rify --windowed --collect-all PySide6 --add-data "mpv;mpv" main.py

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: Rify-Windows
          path: dist/Rify 